name: build-x86-64-immortalwrt-24.10.x

on:
  workflow_dispatch:
    inputs:
      luci_version:
        description: "é€‰æ‹©luciç‰ˆæœ¬"
        required: false
        default: "24.10.5"
        type: choice
        options:
          - 24.10.0
          - 24.10.1
          - 24.10.2
          - 24.10.3
          - 24.10.4
          - 24.10.5
      custom_router_ip:
        description: "è¯·è®¾ç½®è·¯ç”±å™¨çš„ç®¡ç†åœ°å€(ä»…å¯¹å¤šç½‘å£è·¯ç”±å™¨æœ‰æ•ˆ) æ ¼å¼:192.168.x.1 æˆ– 10.x.x.1"
        required: true
        default: "192.168.1.11"
      profile:
        description: "è¯·è¾“å…¥è¦ç¼–è¯‘å›ºä»¶å¤§å° å•ä½(MB)"
        required: true
        default: "2048"
      enable_store:
        description: "é›†æˆ store å•†åº—"
        required: false
        type: boolean
        default: true
      include_docker:
        description: |
          æ˜¯å¦ç¼–è¯‘ Docker æ’ä»¶
        required: true
        default: "yes"
        type: choice
        options:
          - "yes"
          - "no"
      enable_pppoe:
        description: "æ˜¯å¦é…ç½®PPPoEæ‹¨å·ä¿¡æ¯?"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"
      pppoe_account:
        description: "å®½å¸¦è´¦å· (è‹¥å¯ç”¨PPPoE)"
        required: false
      pppoe_password:
        description: "å®½å¸¦å¯†ç  (è‹¥å¯ç”¨PPPoE)"
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x ${{ github.workspace }}/x86-64/build24.sh

      - name: Save Custom Router IP into OpenWrt files
        run: |
          mkdir -p "${{ github.workspace }}/custom"
          echo "${{ github.event.inputs.custom_router_ip }}" > "${{ github.workspace }}/custom/custom_router_ip.txt"
          echo "æ‚¨è®¾ç½®çš„è·¯ç”±å™¨ç®¡ç†åœ°å€æ˜¯:${{ github.event.inputs.custom_router_ip }}"
          # åç»­æ­¥éª¤ä¼šå°†è¯¥æ–‡ä»¶æ˜ å°„åˆ°è·¯ç”±å™¨/etc/config/custom_router_ip.txt ä»¥ä¾¿ç”¨äºå¼€æœºè„šæœ¬99-custom.shè¯»å–ç”¨æˆ·è®¾ç½®çš„ip

      - name: Validate PPPoE Inputs
        run: |
          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
              exit 1
            fi
          fi

      - name: Enable Store integration
        run: |
          if [ "${{ github.event.inputs.enable_store }}" == "true" ]; then
            echo 'CUSTOM_PACKAGES="$CUSTOM_PACKAGES luci-app-store"' >> shell/custom-packages.sh
            echo "âœ… å·²è¿½åŠ  luci-app-store"
          else
            echo "â æœªå¯ç”¨ luci-app-store"
          fi

      - name: ä¿®æ”¹æºç‰ˆæœ¬-${{ github.event.inputs.luci_version }}
        run: |
          # 1. å¤„ç†ç‰¹æ®Šå­—ç¬¦ï¼ˆé¿å… sed è§£ææŠ¥é”™ï¼‰
          LUCI_VERSION="${{ github.event.inputs.luci_version }}"
          # 2. åœ¨æ–‡ä»¶ç¬¬1è¡Œæ’å…¥å˜é‡å®šä¹‰ï¼ˆå¦‚æœæ–‡ä»¶ä¸ºç©ºä¹Ÿèƒ½æ­£å¸¸æ‰§è¡Œï¼‰
          sed -i "1i luci_version=$LUCI_VERSION" x86-64/build24.sh
        shell: bash

      - name: Build ImmortalWrt-x86-64-efi 24.10.x
        run: |
          profile="${{ github.event.inputs.profile }}"
          include_docker="${{ github.event.inputs.include_docker }}"
          luci_version="${{ github.event.inputs.luci_version }}"
          echo "Building for profile: $profile"
          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
            -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
            -v "${{ github.workspace }}/custom:/home/build/immortalwrt/files/etc/config" \
            -v "${{ github.workspace }}/x86-64/imm.config:/home/build/immortalwrt/.config" \
            -v "${{ github.workspace }}/shell:/home/build/immortalwrt/shell" \
            -v "${{ github.workspace }}/x86-64/build24.sh:/home/build/immortalwrt/build.sh" \
            -e PROFILE=$profile \
            -e INCLUDE_DOCKER=$include_docker \
            -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
            -e PPPOE_ACCOUNT=${{ inputs.pppoe_account }} \
            -e PPPOE_PASSWORD=${{ inputs.pppoe_password }} \
          immortalwrt/imagebuilder:x86-64-openwrt-${luci_version} /bin/bash /home/build/immortalwrt/build.sh

      - name: Create info
        run: |
          cat > ${{ github.workspace }}/router-info.md <<EOF
          ## ğŸ“¡ è·¯ç”±å™¨åå°ä¿¡æ¯
          <a href="https://wkdaily.cpolar.cn/archives/1">
           <img src="https://img.shields.io/badge/è‹¥ä¸‹è½½æ…¢å¯å¥—ç”¨å›½å†…åŠ é€Ÿç«™ä¸‹è½½-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
          </a>

          - ğŸ  **åå°åœ°å€**: ${{ github.event.inputs.custom_router_ip }}
          - ğŸ‘¤ **ç”¨æˆ·å**: root
          - ğŸ”‘ **å¯†ç **: æ— 
          EOF

          if [ "${{ github.event.inputs.include_docker }}" == "yes" ]; then
            extra_content="#### é»˜è®¤å¸¦docker"
            echo -e "\n$extra_content" >> ${{ github.workspace }}/router-info.md
          else
            echo -e "\n#### ä¸å¸¦docker" >> ${{ github.workspace }}/router-info.md
          fi

      - name: è·å–æ—¶é—´
        run: |
          TIME="$(TZ='Asia/Shanghai' date +'%Y-%m-%d~%H:%M:%S')"
          echo "TIME=$TIME" >> $GITHUB_ENV
          echo $env.TIME
        shell: bash

      - name: å‹ç¼©bin
        run: |
          tar -zcvf ${{ github.workspace }}/bin/targets/x86/64/ImmortWrt-x86-64-${{ env.TIME }}.tar.gz ${{ github.workspace }}/bin/targets/x86/64/
        shell: bash

      - name: åˆ—å‡º ${{ github.workspace }} æ–‡ä»¶å¤¹çš„æ ‘çŠ¶ç»“æ„
        run: |
          sudo apt update && sudo apt install -y tree
          tree -L 5 ${{ github.workspace }}
        shell: bash

      - name: æä¾›ä¸‹è½½å‹ç¼©åŒ…
        uses: actions/upload-artifact@v4
        with:
          name: ImmortWrt-x86-64-${{ env.TIME }}
          path: ${{ github.workspace }}/bin/targets/x86/64/
          retention-days: 5

      - name: å°† ImmortWrt ä¸Šä¼ ä¸ºå‘å¸ƒèµ„æº
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ImmortWrt-x86-64-${{ env.TIME }}
          body_path: ${{ github.workspace }}/router-info.md
          files: |
            ${{ github.workspace }}/bin/targets/x86/64/*kernel.bin
            ${{ github.workspace }}/bin/targets/x86/64/*rootfs.tar.gz
            ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.img.gz
            ${{ github.workspace }}/bin/targets/x86/64/*squashfs-rootfs.img.gz
            ${{ github.workspace }}/bin/targets/x86/64/*bom.cdx.json
            ${{ github.workspace }}/bin/targets/x86/64/*manifest
            ${{ github.workspace }}/bin/targets/x86/64/profiles.json
            ${{ github.workspace }}/bin/targets/x86/64/sha256sums
            # ${{ github.workspace }}/bin/targets/x86/64/ImmortWrt-x86-64-${{ env.TIME }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
